Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 15.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: stack
          Value: production
        - Key: Name
          Value:
            Fn::ImportValue:
              'Fn::Sub': 'njinin-VPCID'
