Parameters:
  NameVPC:
    Type: String
    Default: 'this-is-my-cpv'
    Description: Name of my VPC

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: stack
          Value: production
        - Key: Name
          Value: !Ref NameVPC

Outputs:
  VPCID:
    Description: My VPC
    Value: !Ref myVPC
  VPCNAME:
    Description: The Name of the VPC
    Value: !Ref NameVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"