Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-094125af156557ca2"
      KeyName: "seaoilstage"
      AvailabilityZone: "us-west-2a"
      UserData:
        Fn::Base64: 
          !Sub |
              #!/bin/bash
              cd ~
              echo "test"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "gp3"
          Iops: "3000"
          DeleteOnTermination: "true"
          VolumeSize: "20"
      - DeviceName: "/dev/sdk"
        NoDevice: {}